AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example Lambda
Resources:
  EchoHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bundle.zip
      Handler: example.echo
      Runtime: python3.6
      Events:
        Submit:
          Type: Api
          Properties:
            Path: /
            Method: get
