AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Example Lambda

# taken almost verbatim from
# http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html
Parameters:
  EnvType:
    Description: Environment type.
    Default: test
    Type: String
    AllowedValues:
      - prod
      - test
    ConstraintDescription: must specify prod or test.
Conditions:
  IsProd: !Equals [ !Ref EnvType, prod ]

Resources:
  EchoHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bundle.zip
      Handler: example.echo
      Runtime: python3.6
      Environment:
        Variables:
          TABLE: !Ref MyTable
      Events:
        Submit:
          Type: Api
          Properties:
            Path: /
            Method: get

  UseTableHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bundle.zip
      Handler: example.use_table
      Runtime: python3.6
      Environment:
        Variables:
          TABLE: !If [IsProd, !Ref MyTable, "some value"]
      Events:
        Submit:
          Type: Api
          Properties:
            Path: /use-table
            Method: get

  MyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "Key"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "Key"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1